### PR TITLE
Added steps and features for transaction log page

### PR DESCRIPTION
**Pull request by jaind1046**

### CODE REVIEW

**Review by NadHodeGW — CHANGES_REQUESTED** [review]
Please remove helper functions from the step file to a different helper file.

**Comment by NadHodeGW** [comment]
@jaind1046 , was this test run successfully through the portal? if not can you run it & confirm?

**Comment by jaind1046** [comment]
> @jaind1046 , was this test run successfully through the portal? if not can you run it & confirm?

Sure I will run it and confirm

**Comment by jaind1046** [comment]
Moving to data driven approach. Merge not needed.Closing

**Pull request closed without merging**
